[package]
name = "blockchain_rust"
version = "0.1.0"
authors = ["Alex <alex@kuznietsov.dev>"]
edition = "2021"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
hex = "0.4.3"
crypto-hash = "0.3.4"
